[build]
  publish = "dist" 
  # Or "build", depending on your output folder. Vite usually defaults to "dist".

[[redirects]]
  from = "/api/*"
  to = "https://variety-urban-attempts-grew.trycloudflare.com/api/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200